version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Django API
      - "80:80"      # Frontend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/heartdisease
      - DEBUG=False
      - SECRET_KEY=your_secret_key_here
    depends_on:
      - db
    volumes:
      - ./health/static:/app/health/static
      - ./health/media:/app/health/media
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=heartdisease
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: 